import { utils } from 'ethers';

// Here the naming is for generality
export const STAKING_VAULT_OWNER_ROLE = 'vaults.StakingVault.owner';
export const STAKING_VAULT_NODE_OPERATOR_ROLE = 'vaults.StakingVault.nodeOperator';
export const STAKING_VAULT_DEPOSITOR_ROLE = 'vaults.StakingVault.depositor';

// DEFAULT_ADMIN_ROLE (bytes32(0))
export const DEFAULT_ADMIN_ROLE = '0x0000000000000000000000000000000000000000000000000000000000000000';
export const DASHBOARD_OWNER_ROLE = 'vaults.Dashboard.owner';

// Everything below are roles in AccessControlEnumerable (AccessControl) contract
export const DASHBOARD_RECOVER_ASSETS_ROLE = 'vaults.Dashboard.RecoverAssets';

export const NODE_OPERATOR_FEE_NODE_OPERATOR_MANAGER_ROLE = 'vaults.NodeOperatorFee.NodeOperatorManagerRole';
export const NODE_OPERATOR_FEE_REWARDS_ADJUST_ROLE = 'vaults.NodeOperatorFee.RewardsAdjustRole';

export const PERMISSIONS_FUND_ROLE = 'vaults.Permissions.Fund';
export const PERMISSIONS_WITHDRAW_ROLE = 'vaults.Permissions.Withdraw';
export const PERMISSIONS_MINT_ROLE = 'vaults.Permissions.Mint';
export const PERMISSIONS_BURN_ROLE = 'vaults.Permissions.Burn';
export const PERMISSIONS_REBALANCE_ROLE = 'vaults.Permissions.Rebalance';
export const PERMISSIONS_PAUSE_BEACON_CHAIN_DEPOSITS_ROLE = 'vaults.Permissions.PauseDeposits';
export const PERMISSIONS_RESUME_BEACON_CHAIN_DEPOSITS_ROLE = 'vaults.Permissions.ResumeDeposits';
export const PERMISSIONS_REQUEST_VALIDATOR_EXIT_ROLE = 'vaults.Permissions.RequestValidatorExit';
export const PERMISSIONS_TRIGGER_VALIDATOR_WITHDRAWAL_ROLE = 'vaults.Permissions.TriggerValidatorWithdrawal';
export const PERMISSIONS_VOLUNTARY_DISCONNECT_ROLE = 'vaults.Permissions.VoluntaryDisconnect';
export const PERMISSIONS_PDG_COMPENSATE_PREDEPOSIT_ROLE = 'vaults.Permissions.PDGCompensatePredeposit';
export const PERMISSIONS_PDG_PROVE_VALIDATOR_ROLE = 'vaults.Permissions.PDGProveValidator';
export const PERMISSIONS_UNGUARANTEED_BEACON_CHAIN_DEPOSIT_ROLE = 'vaults.Permissions.UnguaranteedBeaconChainDeposit';
export const PERMISSIONS_CHANGE_TIER_ROLE = 'vaults.Permissions.ChangeTier';

// For utils.keccak256(utils.toUtf8Bytes(key))
export const ROLE_KEYS = [
  DASHBOARD_OWNER_ROLE,
  DASHBOARD_RECOVER_ASSETS_ROLE,

  NODE_OPERATOR_FEE_NODE_OPERATOR_MANAGER_ROLE,
  NODE_OPERATOR_FEE_REWARDS_ADJUST_ROLE,

  PERMISSIONS_FUND_ROLE,
  PERMISSIONS_WITHDRAW_ROLE,
  PERMISSIONS_MINT_ROLE,
  PERMISSIONS_BURN_ROLE,
  PERMISSIONS_REBALANCE_ROLE,
  PERMISSIONS_PAUSE_BEACON_CHAIN_DEPOSITS_ROLE,
  PERMISSIONS_RESUME_BEACON_CHAIN_DEPOSITS_ROLE,
  PERMISSIONS_REQUEST_VALIDATOR_EXIT_ROLE,
  PERMISSIONS_TRIGGER_VALIDATOR_WITHDRAWAL_ROLE,
  PERMISSIONS_VOLUNTARY_DISCONNECT_ROLE,
  PERMISSIONS_PDG_COMPENSATE_PREDEPOSIT_ROLE,
  PERMISSIONS_PDG_PROVE_VALIDATOR_ROLE,
  PERMISSIONS_UNGUARANTEED_BEACON_CHAIN_DEPOSIT_ROLE,
  PERMISSIONS_CHANGE_TIER_ROLE,
] as const;

export const ROLE_BYTES32 = ROLE_KEYS.map((key) =>
  key === DASHBOARD_OWNER_ROLE ? DEFAULT_ADMIN_ROLE : utils.keccak256(utils.toUtf8Bytes(key)),
);

// For DB/API
export const ALL_ROLE_VALUES = [
  STAKING_VAULT_OWNER_ROLE,
  STAKING_VAULT_NODE_OPERATOR_ROLE,
  STAKING_VAULT_DEPOSITOR_ROLE,

  DASHBOARD_OWNER_ROLE,
  DASHBOARD_RECOVER_ASSETS_ROLE,

  NODE_OPERATOR_FEE_NODE_OPERATOR_MANAGER_ROLE,
  NODE_OPERATOR_FEE_REWARDS_ADJUST_ROLE,

  PERMISSIONS_FUND_ROLE,
  PERMISSIONS_WITHDRAW_ROLE,
  PERMISSIONS_MINT_ROLE,
  PERMISSIONS_BURN_ROLE,
  PERMISSIONS_REBALANCE_ROLE,
  PERMISSIONS_PAUSE_BEACON_CHAIN_DEPOSITS_ROLE,
  PERMISSIONS_RESUME_BEACON_CHAIN_DEPOSITS_ROLE,
  PERMISSIONS_REQUEST_VALIDATOR_EXIT_ROLE,
  PERMISSIONS_TRIGGER_VALIDATOR_WITHDRAWAL_ROLE,
  PERMISSIONS_VOLUNTARY_DISCONNECT_ROLE,
  PERMISSIONS_PDG_COMPENSATE_PREDEPOSIT_ROLE,
  PERMISSIONS_PDG_PROVE_VALIDATOR_ROLE,
  PERMISSIONS_UNGUARANTEED_BEACON_CHAIN_DEPOSIT_ROLE,
  PERMISSIONS_CHANGE_TIER_ROLE,
] as const;
